// Euphoria - Copyright (c) Gustav

#ifndef T3D_EUPHORIA_CONFIG_H_
#define T3D_EUPHORIA_CONFIG_H_

/** @file
Configuration related configurations generated by cmake from t3d-config-in.h
 */
 

#endif  // T3D_EUPHORIA_CONFIG_H_
